### PR TITLE
use PyPI upload workflow from OpenAstronomy

### PR DESCRIPTION
**Pull request by zacharyburnett**
Resolves [SCSB-108](https://jira.stsci.edu/browse/SCSB-108)

This PR changes the PyPI upload process to use the OpenAstronomy workflow instead of the STScI one. The workflow in this PR is configured to test the build with each pull request push, and then publish upon an official release.

### CODE REVIEW

**Comment by BradleySappington** [comment]
@zacharyburnett - If you rebase, this PR should pass tests (can't speak for codecov)

**Comment by mperrin** [comment]
I was reminded of this open PR. @zacharyburnett could you rebase this on current develop please, as @BradleySappington suggested a while back, so we can see if that gets the CI passing? Or I can do so myself if you concur it's OK for me to rebase and push to your PR branch (assuming "allow edits from maintainers" is enabled)?

**Comment by zacharyburnett** [comment]
sure thing, sorry this must have slipped through my notifications

**Comment by mperrin** [comment]
@BradleySappington you approved the version of this PR in the webbpsf repo. I assume this is all good to approve here in poppy as well?

**Review by BradleySappington — APPROVED** [review]

**Pull request merged**
