### PR TITLE
allocate sufficient-sized _surface array even if missing center segment. Fixes #318

### LINKED ISSUE #318: Indexing error in get_opd() of HexSegmentedDeformableMirror() class when center=False
Discovered while testing PR #314 I found a bug in the plotting of a `HexSegmentedDeformableMirror()` instance. When I define it with `center=False`, meaning I omit the center segment, the loop in `get_opd()` still tries to address the full number of segments:

```py
import poppy
import astropy.units as u
import matplotlib.pyplot as plt

iris = poppy.dms.HexSegmentedDeformableMirror(name='Iris DM',
                                              rings=3,
                                              flattoflat=15.*u.m,
                                              gap=2*u.cm,
                                              center=False)
plt.figure(figsize=(16, 8))
iris.display(what='both')
```

Error message:
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-3-56c9b836c811> in <module>()
     11                                               center=False)
     12 plt.figure(figsize=(16, 8))
---> 13 iris.display(what='both')
[...]
~/anaconda/envs/pastis/lib/python3.6/site-packages/poppy/dms.py in get_opd(self, wave)
    594             wseg = self._seg_indices[i]
    595             self.opd[wseg] = (self._surface[i, 0] +
--> 596                               self._surface[i, 1] * self._seg_x[wseg] +
    597                               self._surface[i, 2] * self._seg_y[wseg])
    598         return self.opd

IndexError: index 36 is out of bounds for axis 0 with size 36
```

It works fine with `center=True`:
```python
iris = poppy.dms.HexSegmentedDeformableMirror(name='Iris DM',
                                              rings=3,
                                              flattoflat=15.*u.m,
                                              gap=2*u.cm,
                                              center=True)
plt.figure(figsize=(16, 8))
iris.display(what='both')
```

### PR DESCRIPTION
**Pull request by mperrin**
An alternate way to fix #318. See discussion in comments on #319. 

Attention @ivalaginja

### CODE REVIEW

**Comment by mperrin** [comment]
I can't seem to tag @ivalaginja as a reviewer. Perhaps your account on Github is not marked as a member of the spacetelescope organization?  In any case, Iva, can you please test this and let me know if the fix works for you? It appears all good to me but I'd like to continue making sure all our PRs get reviewed before merging.

**Comment by ivalaginja** [comment]
I will test it. I am part of the space telescope organization though, so this is weird. I'll t ry to figure it out.

**Comment by ivalaginja** [comment]
This seems to work fine since none of my test cases crap out flat-out, but could you rebase this PR on master now that PR #314 is merged? It would allow me to check this in the displays too.

**Comment by mperrin** [comment]
PR rebased onto current master.

**Pull request merged**
