### PR TITLE
Avoid un-padding Fresnel wavefronts when rotating (fixes #572)

### LINKED ISSUE #572: Unexpected modification of the FresnelWavefront matrix size after applying rotation
Dear Poppy team,

Thanks for nice work on Poppy !

I've found an unexpected modification of the FresnelWavefront matrix size after applying rotation using the following code :
```python

import matplotlib.pyplot as plt
import numpy as np
import poppy
import astropy.units as u

w0 = 0.1 # in meter
lamb = 532e-9 # in meter

wf0 = poppy.FresnelWavefront(beam_radius=w0*u.m, wavelength=lamb)
ap = poppy.CircularAperture(radius=w0)
wf0 *= ap

#generate tilt to better see the following rotation
wf0.tilt(Xangle=10.0)

#Display before rotation
plt.figure(figsize=(12,5))
wf0.display('both',colorbar=True, showpadding=True)
plt.suptitle("Before Rotation", fontsize=18)

#Copy wavefront and apply 90° rotation
wf1 = wf0
print('Before rotation:',np.shape(wf1))
wf1.rotate(90.0)
print('After rotation:',np.shape(wf1))

#Display after rotation
plt.figure(figsize=(12,5))
wf1.display('both',colorbar=True, showpadding=True)
plt.suptitle("After rotation", fontsize=18)

``` 
The 2 print outputs are:

Before rotation: (2048, 2048)
After rotation: (1024, 1024)

Displaying amplitude and phase before rotation:
BeforeRotation

Displaying amplitude and phase after rotation:
AfterRotation

As you can see, the matrix size goes from 2048 x 2048 to 1024x1024 and the width of the beam is doubled.
Also this generates the following error while propagating the rotated wavefront 
#
```python
Traceback (most recent call last):

  File "D:\Steve\ProgPython\Poppy\untitled1.py", line 53, in <module>
    wf1.propagate_fresnel(150)

  File "C:\ProgramData\Anaconda3\envs\spyder\lib\site-packages\poppy\utils.py", line 1436, in unit_check_wrapper
    return wrapped_function(*bound_args.args, **bound_args.kwargs)

  File "C:\ProgramData\Anaconda3\envs\spyder\lib\site-packages\poppy\fresnel.py", line 864, in propagate_fresnel
    self._propagate_ptp(delta_z)

  File "C:\ProgramData\Anaconda3\envs\spyder\lib\site-packages\poppy\utils.py", line 1436, in unit_check_wrapper
    return wrapped_function(*bound_args.args, **bound_args.kwargs)

  File "C:\ProgramData\Anaconda3\envs\spyder\lib\site-packages\poppy\fresnel.py", line 730, in _propagate_ptp
    self.wavefront *= exp_t  # eq. 6.68

ValueError: operands could not be broadcast together with shapes (1024,1024) (2048,2048) (1024,1024) 
``` 
Thanks for looking at this issue.

### PR DESCRIPTION
**Pull request by mperrin**
Fixes issue #572. See discussion there about unexpected behavior when rotating Fresnel wavefronts. 

- Refactor the `wavefront.rotate()` method such that the un-padding happens only for Fraunhofer wavefronts, not for Fresnel wavefronts.  The unpadding is moved to a subclass method which only gets called for the Fraunhofer wavefronts, to avoid changing the behavior for those. But Fresnel wavefronts will retain padding when rotated. 
- and some minor cleanup of commented lines in that part of the code.

### CODE REVIEW

**Comment by mperrin** [comment]
query to @obi-wan76 @Skyhawk172 @kian1377 @douglase : is anyone available and willing to review this tiny bug-fix PR?

**Comment by marcio-melendez** [comment]
I ran the short code from the issue ([#572](https://github.com/spacetelescope/poppy/issues/572)) and it is working as intended with the right output dimensions. I can add this comment as a review and approve it, unless someone else wants to do some extra testing. 

Before rotation: (2048, 2048)
After rotation: (2048, 2048)

image

image

**Review by marcio-melendez — APPROVED** [review]
This fix is working as intended. See my previous comments with figures showing the fix that was reported in  #572

**Comment by mperrin** [comment]
Thanks @obi-wan76 !

**Pull request merged**
