### PR TITLE
Dummy PR: Travis

### PR DESCRIPTION
**Pull request by robelgeda**
This PR is for testing Travis CI behavior.

### CODE REVIEW

**Comment by robelgeda** [comment]
That fixed the issue, now remove each part until Travis breaks...

**Comment by robelgeda** [comment]
At this point it looks like the issue is due to MatPlotLib

**Comment by robelgeda** [comment]
Because the MPLBACKEND sets the backend for matplotlib. I have actually run into this when working on the Viz tools. Its caused by requirements for matplotlib not being met. Speaking of which....
https://matplotlib.org/2.0.2/users/installing.html#required-dependencies
screen shot 2018-12-05 at 11 54 50 pm

screen shot 2018-12-05 at 11 51 46 pm

That solves the mystery for why this fixes the bug... but as to why Travis didn't tell us this ¯\_(ツ)_/¯

**Comment by mperrin** [comment]
I’m not sure I follow the point of what you’re highlighting in the package versions - matplotlib 3 requires numpy >1.10, and matplotlib 2 requires numpy >1.7, both of which are easily met by our installing numpy 1.15. So that seems fine? Are you suggesting there’s some version incompatiblity? Sorry I’m not following along...

That said, what’s the minimum versions of all this that the JWST data analysis tools are targeting? Do we have any sort of standard policy for how far back we support? I’d be happy to drop support for some of these older versions. Now would actually be a good time to do that - this is the first Python-3-only release of Poppy and WebbPSF, so it’s distuptive anyways.

**Comment by robelgeda** [comment]
I take that back... that requirement is for matplotlib 2.0.2. I am not sure why the backend was set to something wrong to start with... I can see pyqt being installed and I know it uses `AGG`. Here is some info on the available backends:
https://matplotlib.org/tutorials/introductory/usage.html#backends

**Comment by robelgeda** [comment]
Note that #268 and #267 failed when reran. I merged master now and will check back.

**Comment by robelgeda** [comment]
Looks like they pass once that line of code is added!

**Pull request closed without merging**
